# Generated by Django 5.0.7 on 2024-07-29 18:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Regisseur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeValeurInactive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StockValeurInactive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_unitaire', models.FloatField()),
                ('nombre_de_feuillets', models.PositiveIntegerField()),
                ('montant_total', models.IntegerField(default=0)),
                ('date_enreg', models.DateField(default=datetime.date.today)),
                ('regisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Regisseur.regisseur')),
                ('type_valeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Valeur.typevaleurinactive')),
            ],
        ),
    ]
