# Generated by Django 5.0.7 on 2024-07-29 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Valeur', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockvaleurinactive',
            old_name='date_enreg',
            new_name='date_enregistrement',
        ),
    ]
