# Generated by Django 5.0.7 on 2024-07-29 20:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Regisseur', '0001_initial'),
        ('Valeur', '0002_rename_date_enreg_stockvaleurinactive_date_enregistrement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_unitaire', models.FloatField()),
                ('nombre_de_feuillets', models.PositiveIntegerField()),
                ('montant_total', models.IntegerField(default=0)),
                ('motif', models.TextField(blank=True)),
                ('date_demande', models.DateField(default=datetime.date.today)),
                ('statut', models.CharField(choices=[('en attente', 'En attente'), ('approuvée', 'Approuvée'), ('rejetée', 'Rejetée')], max_length=20)),
                ('regisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Regisseur.regisseur')),
                ('valeur_inactive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Valeur.stockvaleurinactive')),
            ],
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_unitaire', models.FloatField()),
                ('nombre_de_feuillets', models.PositiveIntegerField()),
                ('montant_total', models.IntegerField(default=0)),
                ('date_depot', models.DateField(default=datetime.date.today)),
                ('regisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Regisseur.regisseur')),
                ('type_valeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Valeur.typevaleurinactive')),
            ],
        ),
    ]
