# Generated by Django 5.0.7 on 2024-07-29 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mouvements_de_Stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demande',
            old_name='nombre_de_feuillets',
            new_name='quantite',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='montant_total',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='valeur_unitaire',
        ),
    ]
